"""
Django settings for qa_site project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-uqetn1r-g8tu037z5pv6)#fwhgi!1pl61u97k9&!^$#m_twjj1',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = [h for h in os.environ.get(
    'ALLOWED_HOSTS', '.vercel.app,localhost,127.0.0.1'
).split(',') if h]

# Whether we're running against MongoDB. Set MONGO_URI to a full MongoDB
# connection string to switch over, e.g.:
#   mongodb+srv://<user>:<password>@<cluster>.mongodb.net/?retryWrites=true&w=majority
#
# Read here (not just in DATABASES below) because it also determines which
# contrib AppConfigs and the default auto-field setting we need, since
# MongoDB documents use ObjectId as their primary key instead of an integer.
MONGO_URI = os.environ.get('MONGO_URI')


# Application definition

if MONGO_URI:
    INSTALLED_APPS = [
        # 'qa_site.apps.MongoAdminConfig',
        # 'qa_site.apps.MongoAuthConfig',
        # 'qa_site.apps.MongoContentTypesConfig',
        'django.contrib.sessions',
        'django.contrib.messages',
        'django.contrib.staticfiles',
        'django_mongodb_backend',
        'core',
    ]
else:
    INSTALLED_APPS = [
        'django.contrib.admin',
        'django.contrib.auth',
        'django.contrib.contenttypes',
        'django.contrib.sessions',
        'django.contrib.messages',
        'django.contrib.staticfiles',
        'core',
    ]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'qa_site.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'qa_site.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
#
# Uses MongoDB via the official django-mongodb-backend when MONGO_URI is set
# in the environment. Falls back to SQLite for local development if it
# isn't, so the project still runs out of the box without any setup.
#
# Set these environment variables to use MongoDB:
#   MONGO_URI      - full connection string, e.g.
#                     mongodb+srv://<user>:<password>@<cluster>.mongodb.net/?retryWrites=true&w=majority
#   MONGO_DB_NAME  - optional, database name (defaults to "portfolio")

if MONGO_URI:
    DATABASES = {
        'default': {
            'ENGINE': 'django_mongodb_backend',
            'HOST': MONGO_URI,
            'NAME': os.environ.get('MONGO_DB_NAME', 'portfolio'),
        }
    }
    DATABASE_ROUTERS = ['django_mongodb_backend.routers.MongoRouter']
    # Contrib apps (admin, auth, contenttypes) need their own MongoDB-specific
    # migrations, separate from the default SQL-flavored ones shipped with Django.
    MIGRATION_MODULES = {
        'admin': 'qa_site.mongo_migrations.admin',
        'auth': 'qa_site.mongo_migrations.auth',
        'contenttypes': 'qa_site.mongo_migrations.contenttypes',
    }
else:
    default_sqlite_path = os.environ.get('SQLITE_DB_PATH')
    if not default_sqlite_path and os.environ.get('VERCEL'):
        default_sqlite_path = '/tmp/db.sqlite3'

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': default_sqlite_path or BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}


# Primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field
#
# MongoDB documents use ObjectId as their primary key, so when MONGO_URI is
# set, models default to django_mongodb_backend's ObjectIdAutoField instead
# of Django's usual BigAutoField.

if MONGO_URI:
    DEFAULT_AUTO_FIELD = 'django_mongodb_backend.fields.ObjectIdAutoField'
else:
    DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
